[build]
command = "npm run build"
publish = "dist"

[functions]
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/.netlify/functions/astro-ssr"
status = 200
force = true

## netlify.toml
#[build]
#  command = "npm run build"
#  publish = "dist"
#
#[functions]
#  node_bundler = "esbuild"
#
#[build.environment]
#  NODE_VERSION = "20"
